name: Pipeline CI

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
    secrets:
      sonar-token-backoffice:

env:
  STAGE: ${{ inputs.stage }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Unit Test
        working-directory: BackofficeService/tests/BackofficeService.UnitTests
        run: dotnet test --no-restore --verbosity minimal
      - name: Functional Test
        working-directory: BackofficeService/tests/BackofficeService.FunctionalTests
        run: dotnet test --no-restore --verbosity minimal
      - name: Integration Test
        working-directory: BackofficeService/tests/BackofficeService.IntegrationTests
        run: dotnet test --no-restore --verbosity minimal
  
  scan-sonar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
          dotnet tool install --global dotnet-coverage
      - name: Debug SonarCloud Scanner Installation
        run: ls -R .sonar/scanner
      - name: Install dependencies
        run: dotnet restore
      - name: Test and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar-token-backoffice }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"pradofigu_ms-maestro-producao" /o:"pradofigu" /d:sonar.token="$SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml          
          dotnet-coverage collect "dotnet test BackofficeService/tests/Backoffice.UnitTests/ --no-restore" -f xml -o "coverage.xml" 
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"