name: Pipeline - PRD

on:
  pull_request:
    types: [opened, reopened, ready_for_review, edited, synchronize]
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CD
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/pipeline-cd.yaml
    with:
      stage: prd